### PR TITLE
Use latest go version in Travis CI

### PR DESCRIPTION
**Pull request by ricardopiedade**
Use the latest go versions in Travis CI tests

### CODE REVIEW

**Review by fabiomsouto — APPROVED** [review]
LGTM

**Comment by paulo-ferraz-oliveira** [comment]
We should think about stopping using Travis and move to GitHub actions. Don't know how difficult it would be to do here.

**Comment by fabiomsouto** [comment]
@paulo-ferraz-oliveira something we'll look into soon, thanks for the input.

**Comment by paulo-ferraz-oliveira** [comment]
If it doesn't take me long, I think I might cook something today.

**Pull request merged**
