### PR TITLE
Bump yaml versin to v3

### PR DESCRIPTION
**Pull request by bartigor**
- version bumped for fix error on parsing yaml

### CODE REVIEW

**Comment by fabiomsouto** [comment]
Hey @bartigor,

We'll review this pull request shortly. From a quick glance though:
- Travis CI build is failing
- What issue is this pull request fixing?
- Is the second commit related to the initial pull request? If not, it should be a separate pull request

Cheers

**Comment by bartigor** [comment]
I bumped the version due to the fact that I did not have errors when printing my yaml files with a large degree of nesting.
Parsing fail not correct work on
```
---
key:
  key2
    key3:
    key4:
```
recive map[interface{}] interface{} and string case map[string]interface{}: on expander.go not work

https://github.com/bartigor/gonsul/blob/f511da24e9710f44ca46f54b29206225804ee479/internal/exporter/expander.go#L36
after bump version all work correct

The second change was removed, it belongs to my build system and is not needed here
sory

**Comment by paulo-ferraz-oliveira** [comment]
@bartigor, CI is failing. Is this pull request still something you hope to work on? Thanks.

**Comment by ricardopiedade** [comment]
HI @bartigor we have meanwhile updated Gonsul to use a go version that will support your changes. If you're still interested in applying this change, I ask you to please pull from the current master branch and then create a new pull request .

**Pull request closed without merging**
